POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My product",
    "price": 100.00
}

###

// Command to use SQLite database
// sqllite3 cmd/server/test.db
// SELECT * FROM products;

GET http://localhost:8000/products/64db6ed6-8d5e-4674-813f-bc2ef8043f8f

###
GET http://localhost:8000/products HTTP/1.1

###

PUT http://localhost:8000/products/64db6ed6-8d5e-4674-813f-bc2ef8043f8f
Content-Type: application/json

{
    "name": "I'M A PRODUCT WAS UPDATED",
    "price": 123456789.00
}

###
DELETE http://localhost:8000/products/f7ad97be-ab5a-43f3-aa69-5c29bf97a180

### USER
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Otthon Leão",
    "email": "otthon@mail.com",
    "password": "123456"
}

### USER - GENERATE TOKEN
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "name": "Otthon Leão",
    "email": "otthon@mail.com",
    "password": "123456"
}